services:
  server:
    environment:
      - FLASK_APP=server.py
    entrypoint: 
      # - sleep
      # - infinity
      - flask
      - --debug
      - run
      - --host=0.0.0.0
    volumes: ['.:/app']
